"""Producing-tool profiles: who actually makes a GTFS fix, detected from the feed host.

The scorecard's fixes say what to change. For a small agency the harder question
is often who changes it, because most small agencies do not run their own export.
The feed URL usually answers that: the host serving the zip is, for most of the
registry, the tool or service that produced it. This module maps well-known hosts
to a short profile of how a fix lands there, so fix surfaces can name the actual
next step ("send this to your Trillium contact") instead of the generic "check
your export settings" (docs/RESEARCH-ROADMAP.md R5).

Detection is deliberately conservative. A host either matches a documented
profile or the copy stays generic; guessing wrong would misdirect the one email
a manager sends. Generic hosting (S3 buckets, agency websites) stays unmatched
on purpose — the host says nothing about the producing tool there.
"""

from __future__ import annotations

from dataclasses import dataclass
from urllib.parse import urlparse

# How a fix reaches the published feed, per tool.
#   hosted    — a service produces and hosts the feed; the agency asks them.
#   self_edit — the agency's own staff edit in the tool and re-export.
#   repo      — the feed is regenerated and committed by a repo maintainer.
#   archive   — the URL serves an unmaintained archive copy; fixing any single
#               finding matters less than publishing from a live URL.
KINDS = ("hosted", "self_edit", "repo", "archive")


@dataclass(frozen=True)
class ToolProfile:
    """One producing tool or hosting service the registry sees at scale."""

    key: str
    name: str
    kind: str
    # One or two plain sentences for the agency page: who makes the change and
    # where. Written to the agency reader, never as blame.
    fix_path: str
    # The lede for the forwardable fix-request block, replacing the generic
    # "whoever runs your scheduling software export" copy.
    request_lede: str


_TRILLIUM = ToolProfile(
    key="trillium",
    name="Trillium",
    kind="hosted",
    fix_path=(
        "Trillium produces and hosts this feed as a service. These changes are "
        "made on their side: send the fix list to your Trillium contact and they "
        "apply it and republish."
    ),
    request_lede=(
        "This feed is produced and hosted by Trillium. Copy this and send it to "
        "your Trillium contact; they make the change and republish the feed."
    ),
)

_GTFS_BUILDER = ToolProfile(
    key="gtfs_builder",
    name="National RTAP GTFS Builder",
    kind="self_edit",
    fix_path=(
        "This feed is built with National RTAP's GTFS Builder. Your staff can "
        "usually make these changes in the GTFS Builder spreadsheets and "
        "republish, and National RTAP's help desk supports that at no cost."
    ),
    request_lede=(
        "This feed comes from National RTAP's GTFS Builder, so your own staff can "
        "usually make these changes in the GTFS Builder spreadsheets and "
        "republish. If a consultant maintains it for you, forward this to them."
    ),
)

_REMIX = ToolProfile(
    key="remix",
    name="Remix",
    kind="self_edit",
    fix_path=(
        "This feed is exported from Remix. The change happens in your Remix "
        "workspace; once your planners update the data there, the published "
        "export picks it up."
    ),
    request_lede=(
        "This feed is exported from Remix. If your planners work in Remix, the "
        "change happens in your own workspace; otherwise forward this to whoever "
        "maintains your Remix data."
    ),
)

_PASSIO = ToolProfile(
    key="passio",
    name="Passio",
    kind="hosted",
    fix_path=(
        "This feed is generated by your Passio system from the route and stop "
        "data they maintain. Send the fix list to your Passio contact."
    ),
    request_lede=(
        "This feed is generated by your Passio system. Copy this and send it to "
        "your Passio contact; the fixes apply to the route and stop data behind "
        "your AVL setup."
    ),
)

_REPO = ToolProfile(
    key="repo",
    name="a code repository",
    kind="repo",
    fix_path=(
        "This feed is published from a code repository, so whoever maintains "
        "that repository regenerates the zip — often planning staff or a "
        "consultant. The fix happens in the source data, then a fresh export is "
        "committed."
    ),
    request_lede=(
        "This feed is published from a code repository. Forward this to whoever "
        "maintains that repository; the fix happens in the source data, then a "
        "fresh export is committed."
    ),
)

_ARCHIVE = ToolProfile(
    key="archive",
    name="the TransitFeeds archive",
    kind="archive",
    fix_path=(
        "This feed URL points at the TransitFeeds archive, which is no longer "
        "maintained. Before any single fix, publish the feed from a live URL "
        "you control and update the listings that still point here."
    ),
    request_lede=(
        "This feed is served from the TransitFeeds archive, which is no longer "
        "maintained. The most useful request is publishing the current feed from "
        "a live URL, then these fixes."
    ),
)

# Host suffix -> profile. Matching is suffix-based so vendor subdomains
# (oregon-gtfs.trilliumtransit.com) resolve without listing each one.
_HOST_PROFILES: dict[str, ToolProfile] = {
    "trilliumtransit.com": _TRILLIUM,
    "rapid.nationalrtap.org": _GTFS_BUILDER,
    "gtfs.remix.com": _REMIX,
    "passio3.com": _PASSIO,
    "github.com": _REPO,
    "githubusercontent.com": _REPO,
    "gitlab.com": _REPO,
    "transitfeeds.com": _ARCHIVE,
}


def _host(url: str) -> str:
    netloc = urlparse(url).netloc.lower()
    netloc = netloc.split("@")[-1].split(":")[0]
    return netloc.removeprefix("www.")


def detect_tool(static_url: str | None) -> ToolProfile | None:
    """The producing-tool profile for a feed URL, or None to keep copy generic.

    Suffix match on the host, so both a bare domain and any subdomain of a
    documented service resolve. Anything unrecognized returns None: the fix
    surfaces then keep their existing generic wording.
    """
    if not static_url:
        return None
    host = _host(str(static_url))
    if not host:
        return None
    for suffix, profile in _HOST_PROFILES.items():
        if host == suffix or host.endswith("." + suffix):
            return profile
    return None
